// Tutorial page for shared data updating
// will generate data items and keys as required to demo
// read action will get the selected item, using the selected key
// and display the result in the standard format
import React from "react";
import Article from "../Article";
import XCard from "../XCard";
import TSBossKey from "./TSBossKey";

export default class  extends React.Component {

  render() {

    const props = this.props;

    const xcs= <XCard 
      initiallyExpanded = {true}
      title = {props.title}
      subtitle ={props.subtitle}
      
      content = { 
        <span> 
         <p>
           This boss key has been generated specifically for your use with this tutorial session and will expire later. 
           Any data you create during this session can ony be accessed 
           by keys generated by this boss key. 
           There's no need to note it down as each of the lessons will automatically reference it
         </p>
         
          <TSBossKey tutorial={this.props.tutorial} />

        </span>
      }
    />;
      
   
    
    return (

        <Article 
          title={"Access keys"}
          content={
            <span>
              {xcs}
            </span>
            } 
          subtitle={`a boss key`}
        />  

    );
   
  }
}
 